"""System permission codes seeded for Core (SPEC F.8)."""

from __future__ import annotations

SYSTEM_PERMISSIONS: list[tuple[str, str]] = [
    ("organization.business.read", "Read business profile"),
    ("organization.business.update", "Update business profile"),
    ("organization.branch.create", "Create branch"),
    ("organization.branch.read", "List/read branches"),
    ("organization.location.create", "Create location"),
    ("organization.location.read", "List/read locations"),
    ("security.membership.invite", "Invite members"),
    ("security.membership.read", "List memberships"),
    ("security.membership.suspend", "Suspend membership"),
    ("security.membership.revoke", "Revoke membership"),
    ("security.role.manage", "Manage roles and permissions"),
    ("security.role.assign", "Assign roles to memberships"),
    ("parties.create", "Create party"),
    ("parties.link", "Link party to business"),
    ("parties.read", "Read parties"),
    ("catalog.product.create", "Create product"),
    ("catalog.product.update", "Update product"),
    ("catalog.product.read", "Read products"),
    ("catalog.service.create", "Create service"),
    ("catalog.service.read", "Read services"),
    ("audit.read", "Read audit records"),
    ("catalog.category.create", "Create catalog category"),
    ("catalog.category.read", "Read catalog categories"),
    ("organization.config.manage", "Manage business configuration"),
    ("security.scope.manage", "Manage membership scope assignments"),
    ("organization.entitlements.read", "List business entitlements"),
    ("organization.entitlements.manage", "Grant/revoke business entitlements"),
    ("inventory.stock.read", "Read stock levels and movements"),
    ("inventory.stock.receive", "Receive stock"),
    ("inventory.stock.issue", "Issue stock"),
    ("inventory.stock.adjust", "Adjust stock counts"),
    ("inventory.stock.transfer", "Transfer stock between locations"),
    ("sales.document.manage", "Create and convert sales documents"),
    ("sales.document.finalize", "Finalize invoices and returns"),
    ("sales.payment.record", "Record customer payments"),
    ("purchasing.order.manage", "Create/confirm/cancel purchase orders"),
    ("purchasing.receive", "Create and finalize goods receipts"),
    ("purchasing.payment.record", "Record supplier payments"),
    ("accounting.read", "Read chart of accounts and journals"),
    ("crm.customer.read", "Read customer CRM profile and history"),
    ("crm.customer.manage", "Update CRM profile, notes, credit"),
    ("reporting.read", "Read reporting / analytics projections"),
]
